---
title: "{{< var course.title >}}"
subtitle: "{{< var course.subtitle >}}"
title-block-banner: "img/head.jpg"
toc: false
sidebar: false
---

```{r load_packages, message=FALSE, warning=FALSE, include=FALSE}
library(fontawesome)
library(googlesheets4)
library(gt)
library(gtExtras)
library(tidyverse)
gs4_deauth()

#course_info <- read_sheet("https://docs.google.com/spreadsheets/d/1ijXkRRscKCg-s2V425YP4hEw57b8qQTCU_a7pgMnOWQ/edit?usp=sharing", col_names = c('a','b'))
course_info <- read_sheet("1ijXkRRscKCg-s2V425YP4hEw57b8qQTCU_a7pgMnOWQ", col_names = c('a','b'))


```

{{< var course.aviso >}}

```{r echo=FALSE}

course_info %>% 
  mutate(b = map(b, gt::html)) %>%
  gt() %>% 
  tab_options(column_labels.hidden = TRUE) %>% 
  cols_align(align = "left", columns = b) %>% 
  gt_highlight_rows(
    rows = c(1,3,5),
    fill = "#F0F8FF",
    bold_target_only = TRUE
  )

```

------------------------------------------------------------------------

###### `r fa("university", fill = "steelblue")` [{{< var school.name >}}](%7B%7B%3C%20var%20school.url%20%3E%7D%7D)

###### `r fa("university", fill = "steelblue")` [{{< var university.name >}}](%7B%7B%3C%20var%20university.url%20%3E%7D%7D)
